# Generated by Django 4.1.3 on 2022-11-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='tempo_prepato',
            new_name='tempo_preparo',
        ),
    ]
